<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (!Schema::hasTable('pegawai')) {
            return;
        }

        $connection = Schema::getConnection();
        $grammar = $connection->getQueryGrammar();
        $driver = $connection->getDriverName();

        if ($driver !== 'pgsql') {
            return;
        }

        $columnInfo = $connection->selectOne("SELECT column_default, identity_generation FROM information_schema.columns WHERE table_name = 'pegawai' AND column_name = 'pegawai_id'");

        if ($columnInfo && ($columnInfo->column_default !== null || $columnInfo->identity_generation !== null)) {
            return;
        }

        $connection->statement("ALTER TABLE pegawai ALTER COLUMN pegawai_id ADD GENERATED BY DEFAULT AS IDENTITY");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $connection = Schema::getConnection();
        $driver = $connection->getDriverName();

        if ($driver !== 'pgsql') {
            return;
        }

        $connection->statement("ALTER TABLE pegawai ALTER COLUMN pegawai_id DROP IDENTITY IF EXISTS");
    }
};
