<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $connection = Schema::getConnection();

        if ($connection->getDriverName() !== 'pgsql') {
            return;
        }

        if (Schema::hasTable('approval')) {
            $columnInfo = $connection->selectOne("SELECT column_default, identity_generation FROM information_schema.columns WHERE table_name = 'approval' AND column_name = 'approval_id'");
            if ($columnInfo && $columnInfo->column_default === null && $columnInfo->identity_generation === null) {
                $connection->statement("ALTER TABLE approval ALTER COLUMN approval_id ADD GENERATED BY DEFAULT AS IDENTITY");
            }
        }

        if (Schema::hasTable('notifikasi')) {
            $columnInfo = $connection->selectOne("SELECT column_default, identity_generation FROM information_schema.columns WHERE table_name = 'notifikasi' AND column_name = 'notifikasi_id'");
            if ($columnInfo && $columnInfo->column_default === null && $columnInfo->identity_generation === null) {
                $connection->statement("ALTER TABLE notifikasi ALTER COLUMN notifikasi_id ADD GENERATED BY DEFAULT AS IDENTITY");
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $connection = Schema::getConnection();

        if ($connection->getDriverName() !== 'pgsql') {
            return;
        }

        if (Schema::hasTable('approval')) {
            $connection->statement("ALTER TABLE approval ALTER COLUMN approval_id DROP IDENTITY IF EXISTS");
        }

        if (Schema::hasTable('notifikasi')) {
            $connection->statement("ALTER TABLE notifikasi ALTER COLUMN notifikasi_id DROP IDENTITY IF EXISTS");
        }
    }
};
