<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        if (! Schema::hasTable('nfc')) {
            return;
        }

        $connection = Schema::getConnection();

        if ($connection->getDriverName() !== 'pgsql') {
            return;
        }

        $columnInfo = $connection->selectOne("SELECT column_default, identity_generation FROM information_schema.columns WHERE table_name = 'nfc' AND column_name = 'nfc_id'");

        if ($columnInfo && ($columnInfo->column_default !== null || $columnInfo->identity_generation !== null)) {
            return;
        }

        $connection->statement("ALTER TABLE nfc ALTER COLUMN nfc_id ADD GENERATED BY DEFAULT AS IDENTITY");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $connection = Schema::getConnection();

        if ($connection->getDriverName() !== 'pgsql') {
            return;
        }

        $connection->statement("ALTER TABLE nfc ALTER COLUMN nfc_id DROP IDENTITY IF EXISTS");
    }
};
